before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
  - $(npm bin)/webdriver-manager update
script: $(npm bin)/protractor test/protractor.conf.js --browser=firefox
